spring:
  application:
    name: ronda-dressing-orders
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:postgresql://localhost:5432/ronda
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
