create table public.article
(
    article_id  varchar(255) not null,
    description varchar(255),
    name        varchar(255) not null,
    size        varchar(255),
    primary key (article_id)
);
create table public.guest
(
    height      integer,
    add_date    timestamp(6) not null,
    birth_date  timestamp(6),
    card_number varchar(255) not null,
    name        varchar(255) not null,
    surname     varchar(255) not null,
    primary key (card_number)
);
create table public.order
(
    order_date  timestamp(6),
    state_id    bigint       not null,
    card_number varchar(255),
    order_id    varchar(255) not null,
    primary key (order_id)
);
create table public.order_article
(
    quantity   integer      not null,
    article_id varchar(255) not null,
    order_id   varchar(255) not null,
    primary key (article_id, order_id)
);
create table public.order_state
(
    order_state_id bigint generated by default as identity,
    description    varchar(255) not null,
    primary key (order_state_id)
);
alter table if exists public.order
    add constraint FK26uiamd5tuxvctron2unlr8ig foreign key (card_number) references public.guest;
alter table if exists public.order
    add constraint FKckksaia4crw2s6ihej6i066oj foreign key (state_id) references public.order_state;
alter table if exists public.order_article
    add constraint FKiek77w99i1rqkul18lcqoysp4 foreign key (article_id) references public.article;
alter table if exists public.order_article
    add constraint FK6q2bn8afdjqoev9iqhm6xlxc8 foreign key (order_id) references public.order;
